spring.application.name=angular-app-backend

# MongoDB Connection (Injected via Render Environment Variables)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# JWT Secret Key (Injected via Render Environment Variables)
application.security.jwt.secret-key=${JWT_SECRET_KEY}

# Server Port
server.port=${PORT:8080}

# Logging Configurations
logging.level.org.springframework.security=DEBUG
logging.level.org.mongodb.driver=DEBUG
