spring.application.name=angular-app-backend

logging.level.org.springframework.security=DEBUG
spring.mongodb.uri=mongodb+srv://w3ily10_db_user:EUrAgSMtrF4QZg4x@cluster0.fjmgg4m.mongodb.net/angularapp-database?appName=Cluster0
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970