spring.application.name=angular-app-backend

logging.level.org.springframework.security=DEBUG
spring.mongodb.uri=mongodb+srv://w3ily10_db_user:EUrAgSMtrF4QZg4x@cluster0.fjmgg4m.mongodb.net/angularapp-database?appName=Cluster0
